Week3 | Implementation of Firebase, Filesystem and Jest
aditya-s-19/NodeJS_Training pull request #3
Opened 2024-04-19 10:42 UTC by aditya-s-19

(1) Briefly describe your change.
Added 2 assignments (2 daily )
First assignment if of filesystem and multer
Second assignment shows firebase implementation with CRUD operations

(2) What parts of the application are affected by your change?
None

(3) How did you test your change? If relevant, which role(s) and/or customer configuration(s) did you use?
Yes. I checked with Postman app to test my api

2024-04-19 11:38 UTC, choudhary-keshav approved these changes

2024-04-22 05:29 UTC, choudhary-keshav approved these changes

2024-04-25 04:50 UTC, shreyansh-khatri requested changes

2024-04-25 04:50 UTC, shreyansh-khatri commented on Week-3/Daily-Assignments/firebase-CRUD/firebase.ts
> +    };
this block of code for checking whether user exists is repeated multiple times, try making a separate function for it.

2024-04-25 09:12 UTC, anusreesubash approved these changes

2024-04-29 03:13 UTC, shreyansh-khatri approved these changes

2024-05-16 11:32 UTC, RitikaGarg-ITT approved these changes

2024-05-16 11:40 UTC, merged